### ISSUE TITLE
Release macosx universal wheels

### ISSUE THREAD

**Issue by greglucas** [SWxTREC/pymsis#20]
We should try and release macosx universal wheels. This may be tricky due to the MSIS code itself and the required compiler options to get tests passing. If someone has an ARM machine, they should be able to update some of the extension compiler flags and try compiling and running tests with them.

**Comment by rogervarney** [comment]
Even without a universal wheel, I can confirm that the following trick works on my M1 macbook pro:

ARCHFLAGS="-arch arm64" pip install pymsis

**Comment by greglucas** [comment]
Thanks for letting me know that it works on an M1 @rogervarney! I tried getting wheels built on remote CIs, but unfortunately the gfortran version they have doesn't allow for cross-compiling :( I may try and spin up an M1 VM in AWS and build the wheels and upload those to PyPI, but I can't guarantee when I'll get around to that, so it is good to know that you can build without it.

I did just create a new release as well that moved the build system over to meson, so I'm hopeful that will also build for you on M1 (and maybe doesn't even need the `-arch arm64` explicit specification when building...). Let me know if you have any issues with it though and need anything updated/fixed for that.

**Comment by greglucas** [comment]
I was able to get the wheels built on GitHub's M1 runners now and they have been uploaded to PyPI with the version 0.9 release, so I'm going to close this issue now. We can open a new issue if those wheels don't work or we need something different.
