### ISSUE TITLE
utils.get_f107_ap() returns NaN values for f107a

### ISSUE THREAD

**Issue by cecantrall** [SWxTREC/pymsis#26]
utils.get_f107_ap() returns NaN values for certain dates. Prevents using msis.run() without specifying f107a and prevents using utils.get_f107_ap() before calling msis.run() to specify f107a.

`In: utils.get_f107_ap(np.datetime64(datetime.datetime(2010,12,10)))`
`Out: (86.8, nan, array([1.   , 0.   , 2.   , 0.   , 0.   , 5.375, 5.125]))`

**Comment by cecantrall** [comment]
I just checked NASA Omniweb and they also have missing values on 2011,1,2. 

The f107a calculation could just ignore days that do not have data without a significant impact on the value. The f107 is more tricky. One simple solution would be to replace days without data with the mean of the day before and after. Maybe a warning to the user could be provided when that occurs.

**Comment by greglucas** [comment]
OK, I've switched data providers and taken your suggestion of issuing a warning when that occurs in #29. Let me know what you think over there.

**Comment by cecantrall** [comment]
Apologies for not getting back sooner. Works great. Thank you!

**Comment by greglucas** [comment]
No problem, thanks for the feedback on the design! This is still a pretty early project, so don't hesitate to open other issues if something could be improved further or you hit other roadblocks.
