### ISSUE TITLE
The F10.7 81-days average value miss information

### ISSUE THREAD

**Issue by ROINT** [SWxTREC/pymsis#32]
Dear Developer,

As I try to use the msis2 model, the input parameter is 
```
dates=np.datetime64('2020-12-15T00:00:10')
lons=-69.797
lats=-51.809
alts=504.7
```

And I try to sed the F107 and Ap index is None, so that the model could down the latest space weather data, but it return:
*** ValueError: Input data has non-finite values, all input data must be valid.
I found the `pymsis.utils.get_f107_ap(dates)` return the **f107as** is **nan** (np.nan),
so that cause the main function return the error above.
Is there some way to fix this?

Thank you

**Comment by greglucas** [comment]
The data source has been updated in v0.7.0, so please update to the newly released version and this should work as expected.
