### ISSUE TITLE
ValueError When Running pymsis.calculate with Documentation Example: Cannot Convert Empty String to int32

### ISSUE THREAD

**Issue by ssmong** [SWxTREC/pymsis#71]
[SW-All.csv](https://github.com/user-attachments/files/17964721/SW-All.csv)
**Issue Summary:**  
Executing the example code from the PyMSIS documentation results in a `ValueError`. The error message indicates that an empty string cannot be converted to an `int32` at a specific row and column. This issue prevents users from successfully using the `pymsis.calculate` function as demonstrated in the documentation.

**Steps to Reproduce:**  
1. **Use the following code (identical to the documentation example):**

    ```python
    import pymsis
    import numpy as np

    dates = np.arange(
        np.datetime64("2003-10-28T00:00"),
        np.datetime64("2003-11-04T00:00"),
        np.timedelta64(30, "m")
    )
    # geomagnetic_activity=-1 is a storm-time run
    data = pymsis.calculate(dates, 0, 0, 400, geomagnetic_activity=-1)
    ```

2. **Run the code in your Python environment.**

**Expected Behavior:**  
The `pymsis.calculate` function should execute without errors and return the calculated atmospheric data based on the provided dates and parameters.

**Actual Behavior:**  
A `ValueError` is raised during execution:

```
ValueError: could not convert string '' to int32 at row 24531, column 13.
```

**Error Traceback:**  
```
/usr/local/lib/python3.10/dist-packages/pymsis/utils.py:45: UserWarning: Downloading ap and F10.7 data from https://celestrak.org/SpaceData/SW-All.csv
  warnings.warn(f"Downloading ap and F10.7 data from {_F107_AP_URL}")
/usr/local/lib/python3.10/dist-packages/pymsis/utils.py:45: UserWarning: Downloading ap and F10.7 data from https://celestrak.org/SpaceData/SW-All.csv
  warnings.warn(f"Downloading ap and F10.7 data from {_F107_AP_URL}")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-41-161cc04f4b20> in <cell line: 4>()
      2 dates = np.arange(np.datetime64("2003-10-28T00:00"), np.datetime64("2003-11-04T00:00"), np.timedelta64(30, "m"))
      3 # geomagnetic_activity=-1 is a storm-time run
----> 4 data = pymsis.calculate(dates, 0, 0, 400, geomagnetic_activity=-1)

5 frames
/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py in _read(fname, delimiter, comment, quote, imaginary_unit, usecols, skiplines, max_rows, converters, ndmin, unpack, dtype, encoding)
   1014 
   1015         if read_dtype_via_object_chunks is None:
-> 1016             arr = _load_from_filelike(
   1017                 data, delimiter=delimiter, comment=comment, quote=quote,
   1018                 imaginary_unit=imaginary_unit,

ValueError: could not convert string '' to int32 at row 24531, column 13.
```

**Environment Details:**  
- **Python Version:** 3.11.9 (VSCode), 3.10.12 (Colab)
- **PyMSIS Version:** 0.10.0
- **Operating System:** Window 11 - VSCode and Colab 

Attached file is the one

**Comment by ssmong** [comment]
Thanks for your support!

I just re-ran it, and it worked perfectly fine
Always appreciate your awesome library

**Comment by mananapr** [comment]
> I think we can handle this in the library a little more gracefully too. See #72 for an attempt at skipping those bad lines.

Hi @greglucas, is there a reason we haven't merged the PR yet?
